name: Deploy to staging

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "**.js*"
      - "**.ts*"
      - "package*.json"
      - "Dockerfile"
      - "entrypoint.sh"
      - ".github/workflows/deploy-to-dev.yml"

concurrency:
  # Ensures that only one workflow task will run at a time. Previous builds, if
  # already in process, will get cancelled. Only the latest commit will be allowed
  # to run, cancelling any workflows in between
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      dockerfile_path: ./Dockerfile
      dockerfile_target: runner
      app_name: cuenta-unica-landing
      registry: us-docker.pkg.dev/auth-do/cuenta-unica
    secrets: inherit

  deploy:
    needs: ["build"]
    uses: ./.github/workflows/cloudrun-deploy.yml
    with:
      environment: staging
      project: auth-do
      region: us-east1
      image: us-docker.pkg.dev/auth-do/cuenta-unica/cuenta-unica-landing@${{ needs.build.outputs.image_digest }}
    secrets: inherit
